### ISSUE TITLE
Displacement-force curves

### ISSUE THREAD

**Issue by OVGULIU** [tjhei/cracks#22]
Hi,
where can I find the **displacement-force** curve (output)?
Best

**Comment by tjhei** [comment]
We currently do not output it separately. I typically output the screen text to a file, then filter the lines, and plot using gnuplot:
```
mpirun -n 2 cracks tests/miehe_shear_2.prm | tee log.txt
grep No log.txt >data.txt
gnuplot
> plot "data.txt" using 4:13 w lp
```

**Comment by tjhei** [comment]
That said, we probably should generate a data file in the output directory. I will tackle that at some point.

**Comment by OVGULIU** [comment]
Dear Prof. Heister,

Thanks a lot for your support! & Kind regards
