### ISSUE TITLE
Running the program in Mac

### ISSUE THREAD

**Issue by Arafatk** [tjhei/cracks#32]
Hi,    
Thanks a lot for this software.   
I was wondering if there was a way to run this in Mac?     
I am trying my best but I can't seem to find a proper way to specify the Deal 2 installation directory?

**Comment by tjhei** [comment]
You should be able to specify the deal.II directory with ``cmake -D DEAL_II_DIR=/the/path .`` where `you replace `/the/path`` with where you installed deal.II.

**Comment by tjhei** [comment]
Please comment here if your problem persists. I am closing the issue for now.
