### ISSUE TITLE
Configuring and running cracks

### ISSUE THREAD

**Issue by Botulinumtox** [tjhei/cracks#69]
Hello professor Heister, 

I came across your papers while doing some project at my University, hence I am quite new in the Linux and Deal.II I was wondering if you could give me some advice on how to configure and build deal.ii so I could manage to run your cracks program. 

Which Linux version should I use? 

Can I use: [https://github.com/dealii/candi](https://github.com/dealii/candi) to install deal.ii with all dependencies needed for cracks, so I wouldn't have to bother with installing Trilinos etc.

Also do I need regular Linux platform or is it possible to do through VirtualBox or through Windows10 Ubuntu app. 

I'm sorry if my questions are too simple, but I am really begginer in everything of this.

Thank you in advance

**Comment by tjhei** [comment]
> Can I use: https://github.com/dealii/candi to install deal.ii with all dependencies needed for cracks, so I wouldn't have to bother with installing Trilinos etc.

Yes.

> Also do I need regular Linux platform or is it possible to do through VirtualBox or through Windows10 Ubuntu app.

These options work as well. See the guide at https://www.dealii.org/download.html in the blue box.

> I'm sorry if my questions are too simple, but I am really begginer in everything of this.

Your questions are more about deal.II, so please use https://www.dealii.org/help.html and the forum for questions there.

**Comment by tjhei** [comment]
I am closing this issue here, feel free to write to the deal.II mailing list for questions about deal.II.
