### ISSUE TITLE
Impossible to compile with M1Pro Apple Silicon

### ISSUE THREAD

**Issue by Francyrad** [tjhei/cracks#84]
Dear Professor @tjhei 
I’m sorry to bother you again. I also wanted to use this program beyond aspect, since I had never found one that could simulate the propagation of fractures.

I ran the cmake successfully along with dealii. However, compiling with make fails. I enclose the results here. Am I missing any libraries? Thank you so much again for your help
[cracks_error.txt](https://github.com/tjhei/cracks/files/10699886/cracks_error.txt)

**Comment by tjhei** [comment]
The update in #85 likely fixed compatibility with ARM (but I don't have a system to test right now)
