### ISSUE TITLE
How to create new initial conditions?

### ISSUE THREAD

**Issue by Francyrad** [tjhei/cracks#89]
Dear developers

I've been able to successfully run all the examples. However, It seems that the initial conditions are limited to the tabulated files inside the folder "meshes".

I'd love to create new initial conditions, for example creating new geometries where the crack should open or changing the position of the fracture. Is it possible in someway?

Thank you for the availability

**Comment by tjhei** [comment]
> Is it possible in someway?

It is only possible by going into the code and modifying the boundary conditions, initial conditions, etc. by adding a new ``TestCase``.

**Comment by Francyrad** [comment]
I'll try for sure. It would be amazing if this project, one day, will became customizable like ASPECT directly via .prm
